//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormAuthentication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Freshers_Training2022Entities : DbContext
    {
        public Freshers_Training2022Entities()
            : base("name=Freshers_Training2022Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Form_Department> Form_Department { get; set; }
        public virtual DbSet<Form_Employee> Form_Employee { get; set; }
        public virtual DbSet<Form_Roles> Form_Roles { get; set; }
        public virtual DbSet<Form_UserRolesMapping> Form_UserRolesMapping { get; set; }
        public virtual DbSet<Form_Users> Form_Users { get; set; }
    }
}
