//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormAuthentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_UserRolesMapping
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual Form_Roles Form_Roles { get; set; }
        public virtual Form_Roles Form_Roles1 { get; set; }
        public virtual Form_Users Form_Users { get; set; }
    }
}
