//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendAssesment
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class karthiks_friend
    {
        [Required(ErrorMessage ="Friend ID has to be entered")]
        public int FriendID { get; set; }
        [Required(ErrorMessage ="Friend Name can not be empty")]
        public string FriendName { get; set; }
        [StringLength(25,ErrorMessage ="Place Length cannot exceed 25")]
        public string Place { get; set; }
    }
}
